# Generated by Django 5.1.6 on 2025-07-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='extra_permissions',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='school',
        ),
    ]
