# Generated by Django 5.1.6 on 2025-12-14 03:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Code', 'Code'), ('Try_It', 'Try It'), ('Example', 'Example')], max_length=50)),
                ('text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('order_in_doc', models.IntegerField()),
                ('token_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['page_number', 'order_in_doc'],
            },
        ),
        migrations.CreateModel(
            name='GameZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_message', models.TextField(blank=True, help_text='Detailed status message about current processing step', null=True)),
                ('parsed_pages', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Pages already parsed', size=None)),
                ('total_pages', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', help_text='Content difficulty level', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content_ingestion.gamezone')),
            ],
            options={
                'ordering': ['zone__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('order_in_topic', models.PositiveIntegerField(default=0)),
                ('concept_intent', models.TextField(blank=True, help_text='Description of what to understand (for MiniLM)', null=True)),
                ('code_intent', models.TextField(blank=True, help_text='Description of what to implement (for CodeBERT)', null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_started', 'Not Started')], default='not_started', help_text='Current status of embedding generation', max_length=20)),
                ('embedding_error', models.TextField(blank=True, help_text='Error message if embedding generation failed', null=True)),
                ('embedding_updated_at', models.DateTimeField(auto_now=True, help_text='When the embedding status was last updated')),
                ('document_chunks', models.ManyToManyField(blank=True, help_text='Associated document chunks for this subtopic', related_name='related_subtopics', to='content_ingestion.documentchunk')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='content_ingestion.topic')),
            ],
            options={
                'ordering': ['topic__zone__order', 'order_in_topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TOCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('chunked', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('topic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtopic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_subtopic_title', models.CharField(blank=True, help_text='Third level nesting (optional)', max_length=255, null=True)),
                ('sub_sub_subtopic_title', models.CharField(blank=True, help_text='Fourth level nesting (optional, for expert PDFs)', max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content_ingestion.tocentry')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.uploadeddocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content_ingestion.uploadeddocument'),
        ),
        migrations.CreateModel(
            name='SemanticSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranked_concept_chunks', models.JSONField(blank=True, default=list, help_text='Ranked list of top concept chunks (MiniLM similarities), ordered by similarity (highest first)')),
                ('ranked_code_chunks', models.JSONField(blank=True, default=list, help_text='Ranked list of top code/example/exercise chunks (CodeBERT similarities), ordered by similarity (highest first)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtopic', models.OneToOneField(help_text='The subtopic this semantic analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semantic_data', to='content_ingestion.subtopic')),
            ],
            options={
                'ordering': ['subtopic__name'],
                'indexes': [models.Index(fields=['subtopic'], name='content_ing_subtopi_dad9f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chunk', 'Document Chunk'), ('subtopic', 'Subtopic')], help_text='Type of content being embedded (chunk or subtopic)', max_length=20)),
                ('minilm_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='MiniLM embedding vector (384 dimensions)', null=True, size=384)),
                ('codebert_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='CodeBERT embedding vector (768 dimensions)', null=True, size=768)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', help_text='Name of the embedding model used (e.g., codebert-base, all-MiniLM-L6-v2)', max_length=100)),
                ('model_type', models.CharField(default='sentence', help_text='Type of model: code_bert, sentence', max_length=50)),
                ('dimension', models.IntegerField(default=384, help_text='Actual dimension of the embedding vector')),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('document_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='content_ingestion.documentchunk')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='content_ingestion.subtopic')),
            ],
            options={
                'unique_together': {('document_chunk', 'model_type'), ('subtopic', 'model_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='uniq_content_topic_subtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='tocentry',
            unique_together={('document', 'order')},
        ),
    ]
