# Generated by Django 5.2.4 on 2025-07-16 17:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(help_text='Order in which zones appear', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('parsed_pages', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('total_pages', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('parse_metadata', models.JSONField(blank=True, default=dict, help_text='Stores parsing configuration and metrics')),
            ],
        ),
        migrations.CreateModel(
            name='TOCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 for top-level entries)')),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('chunked', models.BooleanField(default=False, help_text='Set to True once this TOC entry has been parsed and linked to chunks')),
                ('chunk_count', models.IntegerField(default=0)),
                ('next_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_entry_set', to='content_ingestion.tocentry')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content_ingestion.tocentry')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.uploadeddocument')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('document', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(help_text='Order within the zone')),
                ('required_points', models.IntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content_ingestion.gamezone')),
            ],
            options={
                'ordering': ['zone__order', 'order'],
                'unique_together': {('zone', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(help_text='Order within the topic')),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('points_to_unlock', models.IntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('prerequisites', models.ManyToManyField(blank=True, to='content_ingestion.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='content_ingestion.topic')),
            ],
            options={
                'ordering': ['topic__zone__order', 'topic__order', 'order'],
                'unique_together': {('topic', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('Header', 'Header'), ('Module', 'Module'), ('Lesson', 'Lesson'), ('Section', 'Section'), ('Subsection', 'Subsection'), ('Text', 'Text'), ('Table', 'Table'), ('Figure', 'Figure'), ('Code', 'Code'), ('Caption', 'Caption'), ('Exercise', 'Exercise'), ('Example', 'Example')], max_length=50)),
                ('text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('position_on_page', models.JSONField(default=dict, help_text='Coordinates of chunk on the page {x1, y1, x2, y2}')),
                ('order_in_doc', models.IntegerField()),
                ('topic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtopic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score from the parser', null=True)),
                ('parser_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from the parser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content_ingestion.uploadeddocument')),
            ],
            options={
                'ordering': ['page_number', 'order_in_doc'],
            },
        ),
        migrations.CreateModel(
            name='ContentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('mapping_metadata', models.JSONField(blank=True, default=dict)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_ingestion.gamezone')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_ingestion.subtopic')),
                ('toc_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_mappings', to='content_ingestion.tocentry')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_ingestion.topic')),
            ],
            options={
                'unique_together': {('toc_entry', 'zone', 'topic', 'subtopic')},
            },
        ),
    ]
