# Generated by Django 5.2.4 on 2025-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='points_to_unlock',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='required_points',
        ),
        migrations.AddField(
            model_name='gamezone',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Whether this zone is unlocked for play'),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='max_exp',
            field=models.IntegerField(default=1000, help_text='Maximum experience points needed to complete this zone and unlock the next'),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='required_exp',
            field=models.IntegerField(default=0, help_text='Experience points required to unlock this zone'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='difficulty_levels',
            field=models.IntegerField(default=5, help_text='Number of difficulty levels (exercises will be generated for each)'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='min_zone_exp',
            field=models.IntegerField(default=0, help_text='Minimum zone experience required to unlock this subtopic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='min_zone_exp',
            field=models.IntegerField(default=0, help_text='Minimum zone experience required to unlock this topic'),
        ),
    ]
