# Generated by Django 4.2.23 on 2025-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtopic",
            options={"ordering": ["topic__zone__order", "order_in_topic", "name"]},
        ),
        migrations.AddField(
            model_name="subtopic",
            name="order_in_topic",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subtopic",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="subtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="uniq_content_topic_subtopic"
            ),
        ),
    ]
