# Generated by Django 5.1.7 on 2025-07-18 19:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0002_remove_subtopic_points_to_unlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when embedding was generated', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding for semantic search and RAG', null=True, size=1536),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Model used to generate embedding (e.g., text-embedding-3-small)', max_length=100, null=True),
        ),
    ]
