# Generated by Django 4.2.23 on 2025-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_ingestion",
            "0002_alter_subtopic_options_subtopic_order_in_topic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]