# Generated by Django 5.1.7 on 2025-07-18 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0003_documentchunk_embedded_at_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding for semantic search and RAG', null=True, size=384),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Model used to generate embedding (e.g., all-MiniLM-L6-v2)', max_length=100, null=True),
        ),
    ]
