# Generated by Django 5.1.7 on 2025-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0004_alter_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Header', 'Header'), ('Module', 'Module'), ('Lesson', 'Lesson'), ('Section', 'Section'), ('Subsection', 'Subsection'), ('Text', 'Text'), ('Table', 'Table'), ('Figure', 'Figure'), ('Code', 'Code'), ('Caption', 'Caption'), ('Exercise', 'Exercise'), ('Example', 'Example'), ('Concept', 'Concept')], max_length=50),
        ),
    ]
