# Generated by Django 4.2.23 on 2025-09-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_ingestion", "0004_alter_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
