# Generated by Django 5.1.7 on 2025-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0005_alter_documentchunk_chunk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.IntegerField(blank=True, help_text='Number of tokens in the text content (using tiktoken)', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_encoding',
            field=models.CharField(blank=True, default='cl100k_base', help_text='Encoding used for token counting (e.g., cl100k_base for GPT-4)', max_length=50, null=True),
        ),
    ]
