# Generated by Django 5.2.4 on 2025-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0006_documentchunk_token_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='position_on_page',
        ),
        migrations.AddField(
            model_name='tocentry',
            name='subtopic_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='topic_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Example', 'Example'), ('Try_It', 'Try It'), ('Text', 'Text'), ('Code', 'Code'), ('Table', 'Table'), ('Figure', 'Figure')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ContentMapping',
        ),
    ]
