# Generated by Django 5.1.7 on 2025-07-23 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0007_remove_documentchunk_position_on_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='description_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding of subtopic description for semantic matching with content chunks', null=True, size=384),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When the embedding was generated', null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedding_model',
            field=models.CharField(blank=True, default='all-MiniLM-L6-v2', help_text='Model used to generate the embedding', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding of topic description for semantic matching with content chunks', null=True, size=384),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When the embedding was generated', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding_model',
            field=models.CharField(blank=True, default='all-MiniLM-L6-v2', help_text='Model used to generate the embedding', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Example', 'Example'), ('Try_It', 'Try It'), ('Text', 'Text'), ('Code', 'Code'), ('Table', 'Table'), ('Figure', 'Figure'), ('Introduction', 'Introduction'), ('Acknowledgement', 'Acknowledgement'), ('TOC', 'Table of Contents'), ('Index', 'Index'), ('Header', 'Header'), ('Meta', 'Meta')], max_length=50),
        ),
    ]
