# Generated by Django 5.1.7 on 2025-07-26 18:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0008_add_topic_subtopic_embeddings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['page', 'order']},
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='order_in_doc',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='page_number',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='parser_metadata',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='token_count',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='token_encoding',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='max_exp',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='required_exp',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='description_embedding',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='difficulty_levels',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='min_zone_exp',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='chunk_count',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='chunked',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='next_entry',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='subtopic_title',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='topic_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description_embedding',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='min_zone_exp',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='parsed_pages',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Intended difficulty of the source material.', max_length=16),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Example', 'Example'), ('Code', 'Code')], max_length=16),
        ),
        migrations.AlterField(
            model_name='gamezone',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamezone',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tocentry',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='parse_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=384)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('document_chunk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_obj', to='content_ingestion.documentchunk')),
                ('subtopic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_obj', to='content_ingestion.subtopic')),
            ],
        ),
    ]
