# Generated by Django 5.1.7 on 2025-07-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0009_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='description',
        ),
    ]
