# Generated by Django 5.1.6 on 2025-07-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0010_remove_subtopic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamezone',
            name='is_unlocked',
        ),
    ]
