# Generated by Django 5.1.7 on 2025-07-29 15:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0010_remove_subtopic_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['page_number', 'order_in_doc']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order', 'topic__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['zone__order', 'name']},
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='order',
            new_name='order_in_doc',
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='page',
            new_name='page_number',
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='status',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='parser_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_encoding',
            field=models.CharField(blank=True, default='cl100k_base', max_length=50),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='max_exp',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='required_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='description_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedding_model',
            field=models.CharField(blank=True, default='all-MiniLM-L6-v2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='chunked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='subtopic_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='topic_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='parsed_pages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Pages already parsed', size=None),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Example', 'Example'), ('Try_It', 'Try It'), ('Code', 'Code')], max_length=50),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='document_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='content_ingestion.documentchunk'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='model_name',
            field=models.CharField(default='all-MiniLM-L6-v2', help_text='Model used to produce this embedding', max_length=100),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='content_ingestion.subtopic'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Embedding vector', size=384),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='intermediate', help_text='Content difficulty level', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('document_chunk', 'model_name'), ('subtopic', 'model_name')},
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='order',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
