# Generated by Django 5.1.7 on 2025-07-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0011_alter_documentchunk_options_alter_subtopic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='description_embedding',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='embedding_model',
        ),
    ]
