# Generated by Django 5.1.7 on 2025-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0012_remove_subtopic_description_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Exercise', 'Exercise'), ('Code', 'Code'), ('Try_It', 'Try It'), ('Example', 'Example')], max_length=50),
        ),
    ]
