# Generated by Django 5.1.7 on 2025-07-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0013_alter_documentchunk_chunk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
    ]
