# Generated by Django 5.1.7 on 2025-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0014_remove_chunk_embedding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='sub_subtopic_title',
            field=models.CharField(blank=True, help_text='Third level nesting (optional, only when detected in TOC)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='sub_subtopic_title',
            field=models.CharField(blank=True, help_text='Third level nesting (optional)', max_length=255, null=True),
        ),
    ]
