# Generated by Django 5.1.7 on 2025-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0015_add_sub_subtopic_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='sub_sub_subtopic_title',
            field=models.CharField(blank=True, help_text='Fourth level nesting (optional, for expert-level PDFs with deep hierarchy)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tocentry',
            name='sub_sub_subtopic_title',
            field=models.CharField(blank=True, help_text='Fourth level nesting (optional, for expert PDFs)', max_length=255, null=True),
        ),
    ]
