# Generated by Django 5.1.7 on 2025-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0016_add_level4_sub_sub_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='unmatched', help_text='Status for semantic similarity matching - can be used to ignore already processed chunks', max_length=20),
        ),
    ]
