# Generated by Django 5.1.7 on 2025-08-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0017_add_match_status_to_documentchunk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('document_chunk',), ('subtopic',)},
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='max_exp',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='required_exp',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='parse_metadata',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='embedding',
            name='model_name',
        ),
    ]
