# Generated by Django 5.1.6 on 2025-07-31 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0011_remove_gamezone_is_unlocked'),
        ('content_ingestion', '0017_add_match_status_to_documentchunk'),
    ]

    operations = [
    ]
