# Generated by Django 5.1.7 on 2025-08-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0018_remove_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='token_encoding',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='match_status',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='topic_title',
        ),
        migrations.RunSQL(
            # Clean up parser_metadata by removing 'fallback_granular' source entries (PostgreSQL syntax)
            """
            UPDATE content_ingestion_documentchunk 
            SET parser_metadata = parser_metadata - 'source'
            WHERE parser_metadata->>'source' = 'fallback_granular';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
