# Generated by Django 5.1.6 on 2025-07-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0018_merge_20250731_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamezone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='required_exp',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='is_unlocked',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
