# Generated by Django 5.1.6 on 2025-07-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0019_remove_gamezone_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='order',
        ),
    ]
