# Generated by Django 5.1.7 on 2025-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0019_remove_unused_documentchunk_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='sub_sub_subtopic_title',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='sub_subtopic_title',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='parser_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores book title, extraction method, and other processing metadata'),
        ),
    ]
