# Generated by Django 5.1.7 on 2025-08-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0019_remove_unused_documentchunk_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='sub_subtopic_title',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='sub_sub_subtopic_title',
        ),
    ]
