# Generated by Django 5.1.6 on 2025-07-31 02:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0020_remove_subtopic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order', 'topic__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['zone__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='gamezone',
            name='max_exp',
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('zone', 'order')},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'order')},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_unlocked',
        ),
    ]
