# Generated by Django 5.1.7 on 2025-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0020_remove_documentchunk_sub_sub_subtopic_title_and_more'),
    ]

    operations = [
    ]
