# Generated by Django 5.1.6 on 2025-07-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0021_alter_subtopic_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
    ]
