# Generated by Django 5.1.7 on 2025-08-07 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0021_merge_20250808_0225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='embedding',
            name='dimension',
            field=models.IntegerField(default=384, help_text='Actual dimension of the embedding vector'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='model_name',
            field=models.CharField(default='all-MiniLM-L6-v2', help_text='Name of the embedding model used (e.g., codebert-base, all-MiniLM-L6-v2)', max_length=100),
        ),
        migrations.AddField(
            model_name='embedding',
            name='model_type',
            field=models.CharField(default='sentence', help_text='Type of model: code_bert, sentence, general', max_length=50),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Embedding vector - dimension depends on model used', size=768),
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('document_chunk', 'model_type'), ('subtopic', 'model_type')},
        ),
    ]
