# Generated by Django 5.1.7 on 2025-08-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0020_remove_additional_hierarchy_fields'),
        ('content_ingestion', '0022_alter_embedding_unique_together_embedding_dimension_and_more'),
    ]

    operations = [
    ]
