# Generated by Django 5.1.6 on 2025-07-31 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0022_alter_subtopic_options_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order', 'topic__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['zone__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.gamezone'),
        ),
    ]
