# Generated by Django 5.1.6 on 2025-07-31 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0023_alter_subtopic_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
