# Generated by Django 5.1.7 on 2025-08-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0024_remove_parsed_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', help_text='Content difficulty level', max_length=20),
        ),
        migrations.CreateModel(
            name='SemanticSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranked_chunks', models.JSONField(blank=True, default=list, help_text='Ranked list of top 10 chunk IDs with similarity scores, ordered by similarity (highest first)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtopic', models.OneToOneField(help_text='The subtopic this semantic analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semantic_data', to='content_ingestion.subtopic')),
            ],
            options={
                'ordering': ['subtopic__name'],
                'indexes': [models.Index(fields=['subtopic'], name='content_ing_subtopi_dad9f8_idx')],
            },
        ),
    ]
