# Generated by Django 5.1.6 on 2025-07-31 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0024_topic_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['zone__order']},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('zone',)},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
