# Generated by Django 5.1.7 on 2025-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0025_alter_uploadeddocument_difficulty_semanticsubtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
