# Generated by Django 5.1.6 on 2025-07-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0025_alter_subtopic_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order']},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic',)},
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='order',
        ),
    ]
