# Generated by Django 5.1.7 on 2025-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0026_add_uploaded_at_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='parser_metadata',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='subtopic_title',
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
