# Generated by Django 5.1.6 on 2025-07-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0026_alter_subtopic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['zone__order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
    ]
