# Generated by Django 5.1.6 on 2025-07-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0027_alter_topic_options_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__zone__order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
    ]
