# Generated by Django 5.1.7 on 2025-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0027_remove_subtopic_and_metadata_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='embedding',
            name='content_type',
            field=models.CharField(choices=[('chunk', 'Document Chunk'), ('subtopic', 'Subtopic')], default='chunk', help_text='Type of content being embedded (chunk or subtopic)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('document_chunk', 'model_type', 'content_type'), ('subtopic', 'model_type', 'content_type')},
        ),
    ]
