# Generated by Django 5.1.7 on 2025-08-15 08:07

from django.db import migrations


def populate_content_type(apps, schema_editor):
    """Populate content_type field based on existing foreign keys."""
    Embedding = apps.get_model('content_ingestion', 'Embedding')
    
    # Update embeddings with document_chunk
    Embedding.objects.filter(document_chunk__isnull=False).update(content_type='chunk')
    
    # Update embeddings with subtopic
    Embedding.objects.filter(subtopic__isnull=False).update(content_type='subtopic')


def reverse_populate_content_type(apps, schema_editor):
    """Reverse migration - set all content_type back to default."""
    Embedding = apps.get_model('content_ingestion', 'Embedding')
    Embedding.objects.all().update(content_type='chunk')


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0028_add_content_type_to_embedding'),
    ]

    operations = [
        migrations.RunPython(populate_content_type, reverse_populate_content_type),
    ]
