# Generated by Django 5.1.7 on 2025-08-15 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0029_populate_content_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='codebert_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='CodeBERT embedding vector (768 dimensions)', null=True, size=768),
        ),
        migrations.AddField(
            model_name='embedding',
            name='minilm_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='MiniLM embedding vector (384 dimensions)', null=True, size=384),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='content_type',
            field=models.CharField(choices=[('chunk', 'Document Chunk'), ('subtopic', 'Subtopic')], help_text='Type of content being embedded (chunk or subtopic)', max_length=20),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Legacy embedding vector field', null=True, size=768),
        ),
    ]
