# Generated by Django 5.1.7 on 2025-08-15 08:44

from django.db import migrations, models


def migrate_vectors_to_new_fields(apps, schema_editor):
    """Migrate existing vectors from the legacy 'vector' field to appropriate new fields."""
    Embedding = apps.get_model('content_ingestion', 'Embedding')
    
    # Migrate MiniLM vectors (sentence model, 384 dimensions)
    minilm_embeddings = Embedding.objects.filter(
        model_type='sentence',
        vector__isnull=False,
        minilm_vector__isnull=True
    )
    minilm_count = 0
    for embedding in minilm_embeddings:
        embedding.minilm_vector = embedding.vector
        embedding.save()
        minilm_count += 1
    
    # Migrate CodeBERT vectors (code_bert model, 768 dimensions)  
    codebert_embeddings = Embedding.objects.filter(
        model_type='code_bert',
        vector__isnull=False,
        codebert_vector__isnull=True
    )
    codebert_count = 0
    for embedding in codebert_embeddings:
        embedding.codebert_vector = embedding.vector
        embedding.save()
        codebert_count += 1
    
    print(f"Migrated {minilm_count} MiniLM vectors")
    print(f"Migrated {codebert_count} CodeBERT vectors")


def reverse_migrate_vectors(apps, schema_editor):
    """Reverse migration - copy vectors back to legacy field."""
    Embedding = apps.get_model('content_ingestion', 'Embedding')
    
    # Copy MiniLM vectors back
    for embedding in Embedding.objects.filter(minilm_vector__isnull=False, vector__isnull=True):
        embedding.vector = embedding.minilm_vector
        embedding.save()
    
    # Copy CodeBERT vectors back  
    for embedding in Embedding.objects.filter(codebert_vector__isnull=False, vector__isnull=True):
        embedding.vector = embedding.codebert_vector
        embedding.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0030_add_dual_vector_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_vectors_to_new_fields, reverse_migrate_vectors),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0030_add_dual_vector_fields'),
    ]

    operations = [
    ]
