# Generated by Django 5.1.7 on 2025-08-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0031_migrate_existing_vectors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('document_chunk', 'model_type'), ('subtopic', 'model_type')},
        ),
    ]
