# Generated by Django 5.1.7 on 2025-08-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0032_fix_embedding_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='vector',
        ),
    ]
