# Generated by Django 5.1.7 on 2025-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0033_remove_legacy_vector_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticsubtopic',
            name='ranked_code_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Ranked list of top code/example/exercise chunks (CodeBERT similarities), ordered by similarity (highest first)'),
        ),
        migrations.AddField(
            model_name='semanticsubtopic',
            name='ranked_concept_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Ranked list of top concept chunks (MiniLM similarities), ordered by similarity (highest first)'),
        ),
        migrations.AlterField(
            model_name='semanticsubtopic',
            name='ranked_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Legacy field - use ranked_concept_chunks and ranked_code_chunks instead'),
        ),
    ]
