# Generated by Django 5.1.7 on 2025-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0034_add_separate_concept_code_rankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='code_intent',
            field=models.TextField(blank=True, help_text='Code-focused description for CodeBERT embedding - explains what to implement', null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='concept_intent',
            field=models.TextField(blank=True, help_text='Conceptual description for MiniLM embedding - explains what to understand', null=True),
        ),
    ]
