# Generated by Django 5.1.7 on 2025-08-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0035_subtopic_code_intent_subtopic_concept_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semanticsubtopic',
            name='ranked_chunks',
        ),
    ]
