# Generated by Django 5.1.7 on 2025-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0036_remove_semanticsubtopic_ranked_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamezone',
            name='is_unlocked',
        ),
        migrations.AlterField(
            model_name='embedding',
            name='model_type',
            field=models.CharField(default='sentence', help_text='Type of model: code_bert, sentence', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='code_intent',
            field=models.TextField(blank=True, help_text='Description of what to implement (for CodeBERT)', null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='concept_intent',
            field=models.TextField(blank=True, help_text='Description of what to understand (for MiniLM)', null=True),
        ),
    ]
