# Generated by Django 5.1.7 on 2025-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0037_remove_gamezone_is_unlocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
