# Generated by Django 5.1.7 on 2025-08-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0019_add_processing_message'),
        ('content_ingestion', '0038_add_soft_delete'),
    ]

    operations = [
    ]
