# Generated by Django 5.1.7 on 2025-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0039_merge_20250819_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='embedding_error',
            field=models.TextField(blank=True, help_text='Error message if embedding generation failed', null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedding_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], default='draft', help_text='Publication status of the subtopic', max_length=20),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='embedding_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the embedding status was last updated'),
        ),
    ]
