# Generated by Django 5.1.7 on 2025-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0040_subtopic_embedding_error_subtopic_embedding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='document_chunks',
            field=models.ManyToManyField(blank=True, help_text='Associated document chunks for this subtopic', related_name='related_subtopics', to='content_ingestion.documentchunk'),
        ),
    ]
