# Generated by Django 5.1.7 on 2025-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0041_subtopic_document_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_started', 'Not Started')], default='not_started', help_text='Current status of embedding generation', max_length=20),
        ),
    ]
