# Generated by Django 4.2.26 on 2025-12-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question_generation", "0001_initial"),
        ("minigames", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hangmandata",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hangman_data",
                to="minigames.gamesession",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamequestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_sessions",
                to="question_generation.generatedquestion",
            ),
        ),
        migrations.AddField(
            model_name="gamequestion",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_questions",
                to="minigames.gamesession",
            ),
        ),
        migrations.AddField(
            model_name="crossworddata",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crossword_data",
                to="minigames.gamesession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamequestion", unique_together={("session", "question")},
        ),
    ]
