# Generated by Django 5.1.6 on 2025-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('crossword', 'Crossword'), ('hangman', 'Hangman'), ('wordsearch', 'WordSearch')], max_length=50),
        ),
    ]
