# Generated by Django 5.1.6 on 2025-07-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_alter_gamesession_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField()),
                ('placements', models.JSONField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wordsearch_data', to='minigames.gamesession')),
            ],
        ),
    ]
