# Generated by Django 5.1.6 on 2025-07-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0004_question_function_name_question_hidden_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='broken_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('crossword', 'Crossword'), ('hangman', 'Hangman'), ('wordsearch', 'WordSearch'), ('debugging', 'Debugging')], max_length=50),
        ),
    ]
