# Generated by Django 5.1.6 on 2025-07-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0005_question_broken_code_alter_gamesession_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='source_type',
        ),
        migrations.AddField(
            model_name='question',
            name='game_type',
            field=models.CharField(blank=True, choices=[('crossword', 'Crossword'), ('hangman', 'Hangman'), ('wordsearch', 'WordSearch'), ('debugging', 'Debugging')], help_text='Game this question is for', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(blank=True, choices=[('crossword', 'Crossword'), ('hangman', 'Hangman'), ('wordsearch', 'WordSearch'), ('debugging', 'Debugging')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gamequestion',
            unique_together={('session', 'question')},
        ),
        migrations.AddField(
            model_name='question',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='minigames.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='minigames.topic'),
        ),
    ]
