# Generated by Django 5.1.6 on 2025-07-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0006_subtopic_topic_remove_question_source_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopics',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
    ]
