# Generated by Django 5.1.6 on 2025-08-10 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0007_remove_subtopic_topic_remove_question_subtopics_and_more'),
        ('question_generation', '0002_alter_generatedquestion_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_sessions', to='question_generation.generatedquestion'),
        ),
    ]
