# Generated by Django 4.2.23 on 2025-08-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0002_generatedquestion"),
        ("minigames", "0007_remove_subtopic_topic_remove_question_subtopics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamequestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_sessions",
                to="question_generation.generatedquestion",
            ),
        ),
    ]
