# Generated by Django 4.2.23 on 2025-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minigames", "0008_alter_gamequestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("master", "Master"),
                ],
                max_length=12,
            ),
        ),
    ]
