# Generated by Django 5.1.6 on 2025-08-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0008_alter_gamequestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.JSONField()),
                ('placements', models.JSONField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crossword_data', to='minigames.gamesession')),
            ],
        ),
    ]
