# Generated by Django 4.2.23 on 2025-08-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0003_alter_generatedquestion_difficulty_and_more"),
        ("minigames", "0009_alter_question_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="question_generation.generatedquestion",
            ),
        ),
    ]
