# Generated by Django 5.1.6 on 2025-12-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubtopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTopicProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_percent', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserZoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percent', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['zone__order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubtopicLearningRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pT_scale', models.FloatField(default=1.0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.subtopic')),
            ],
        ),
    ]
