# Generated by Django 4.2.24 on 2025-09-08 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_ingestion', '0002_alter_subtopic_options_subtopic_order_in_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percent', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_zones', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.gamezone')),
            ],
            options={
                'ordering': ['zone__order'],
                'unique_together': {('user', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='UserTopicProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_percent', models.FloatField(default=0.0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserSubtopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subtopic')},
            },
        ),
    ]
