# Generated by Django 4.2.26 on 2025-12-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content_ingestion", "0001_initial"),
        ("user_learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userzoneprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unlocked_zones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userzoneprogress",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_ingestion.gamezone",
            ),
        ),
        migrations.AddField(
            model_name="usertopicproficiency",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_ingestion.topic",
            ),
        ),
        migrations.AddField(
            model_name="usertopicproficiency",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_proficiencies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersubtopicmastery",
            name="subtopic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_ingestion.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="usersubtopicmastery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopic_mastery",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersubtopiclearningrate",
            name="subtopic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_ingestion.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="usersubtopiclearningrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userzoneprogress", unique_together={("user", "zone")},
        ),
        migrations.AlterUniqueTogether(
            name="usertopicproficiency", unique_together={("user", "topic")},
        ),
        migrations.AlterUniqueTogether(
            name="usersubtopicmastery", unique_together={("user", "subtopic")},
        ),
        migrations.AlterUniqueTogether(
            name="usersubtopiclearningrate", unique_together={("user", "subtopic")},
        ),
    ]
