# Generated by Django 5.1.6 on 2025-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubtopicmastery',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='usersubtopicmastery',
            name='correct',
        ),
        migrations.AddField(
            model_name='usersubtopicmastery',
            name='mastery_level',
            field=models.FloatField(default=0.0),
        ),
    ]
