# Generated by Django 5.1.6 on 2025-07-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_learning', '0002_remove_usersubtopicmastery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userzoneprogress',
            name='completion_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
