# Generated by Django 5.1.6 on 2025-07-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_learning', '0003_userzoneprogress_completion_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertopicproficiency',
            options={},
        ),
    ]
