# Generated by Django 4.2.29 on 2026-04-10 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userability',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irt_ability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_responses', to='question_generation.generatedquestion'),
        ),
        migrations.AddField(
            model_name='itemirtparameters',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irt_params', to='question_generation.generatedquestion'),
        ),
    ]
