# Generated by Django 4.2.26 on 2025-12-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userability",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irt_ability",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_responses",
                to="question_generation.generatedquestion",
            ),
        ),
        migrations.AddField(
            model_name="itemirtparameters",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irt_params",
                to="question_generation.generatedquestion",
            ),
        ),
    ]
