# Generated by Django 4.2.23 on 2025-09-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_responses",
                to="question_generation.generatedquestion",
            ),
        ),
    ]
