# Generated by Django 4.2.23 on 2025-09-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_generation",
            "0002_generatedquestion_recalibrated_difficulty_and_more",
        ),
        ("analytics", "0002_alter_questionresponse_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRecalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_difficulty", models.CharField(max_length=20)),
                ("new_difficulty", models.CharField(max_length=20)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recalibration_history",
                        to="question_generation.generatedquestion",
                    ),
                ),
            ],
        ),
    ]
