"""
Django settings for pygrounds_backend_new project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from decouple import config
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import multiprocessing

load_dotenv()

# Dynamic worker configuration based on CPU cores and generation hierarchy
def get_layered_worker_count(difficulty_workers: int = 4, topic_workers: int = 8, subtopic_workers: int = 16) -> int:
    """
    Calculate optimal worker count using layered scaling approach.

    Layered scaling considers the natural hierarchy of question generation:
    1. Difficulty level (easy, intermediate, advanced, master) - base layer
    2. Topic level (different topics within zones) - medium layer
    3. Subtopic level (individual subtopics) - high layer

    Args:
        difficulty_workers: Workers for difficulty-level parallelism
        topic_workers: Workers for topic-level parallelism
        subtopic_workers: Workers for subtopic-level parallelism

    Returns:
        Optimal worker count based on CPU cores and generation hierarchy
    """
    cpu_count = multiprocessing.cpu_count()

    # Layered scaling based on CPU cores
    if cpu_count <= 4:
        # Low-end systems: stick to difficulty-level parallelism
        return min(difficulty_workers, cpu_count)
    elif cpu_count <= 8:
        # Medium systems: add topic-level parallelism
        return min(topic_workers, cpu_count)
    else:
        # High-end systems: add subtopic-level parallelism (conservative to prevent DB connection exhaustion)
        return min(subtopic_workers, cpu_count)


# Dynamic worker configuration based on question type and database load
# Different question types have different database query patterns:
# - Non-coding: Efficient queries, can use full CPU scaling (up to 16)
# - Pre-assessment: Similar to non-coding, can use full CPU scaling (up to 16)
# - Coding: Multiple queries + fallbacks, fixed at 4 to prevent connection exhaustion

def get_workers_for_game_type(game_type: str) -> int:
    """
    Get optimal worker count based on question type to prevent database connection exhaustion.
    
    Args:
        game_type: 'coding', 'non_coding', or 'pre_assessment'
    
    Returns:
        Optimal worker count for the given game type
    """
    cpu_count = multiprocessing.cpu_count()
    
    if game_type == 'coding':
        # Coding questions do more DB queries (initial + fallback), so use fixed conservative count
        return 4  # Fixed at 4 to prevent "too many clients" errors
    elif game_type in ['non_coding', 'pre_assessment']:
        # Non-coding and pre-assessment are efficient, use full dynamic scaling like before
        return get_layered_worker_count(difficulty_workers=4, topic_workers=8, subtopic_workers=16)
    else:
        # Default fallback
        return 4

# Question generation worker configuration
# Base configuration - can be overridden per game type
QUESTION_GENERATION_WORKERS = 4
CODING_QUESTION_WORKERS = get_workers_for_game_type('coding')          # Fixed at 4
NON_CODING_QUESTION_WORKERS = get_workers_for_game_type('non_coding')  # Dynamic up to 16
PRE_ASSESSMENT_WORKERS = get_workers_for_game_type('pre_assessment')   # Dynamic up to 16

def get_optimal_worker_count(base_workers: int = 4, max_workers: int = 16) -> int:
    """
    Legacy function for backward compatibility.
    Use get_layered_worker_count() for new implementations.
    """
    return get_layered_worker_count(difficulty_workers=base_workers, subtopic_workers=max_workers)

# Worker configuration constants - layered scaling approach
# QUESTION_GENERATION_WORKERS: Subtopic-level parallelism (highest granularity)
# EMBEDDING_WORKERS: Topic-level parallelism (medium granularity)
# DOCUMENT_PROCESSING_WORKERS: Difficulty-level parallelism (lowest granularity)

QUESTION_GENERATION_WORKERS = 4
EMBEDDING_WORKERS = 2
DOCUMENT_PROCESSING_WORKERS = 2

# Legacy constants for backward compatibility
DEFAULT_MAX_WORKERS = QUESTION_GENERATION_WORKERS

# Suppress TensorFlow warnings and logs
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Suppress all TF logs except errors
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'  # Disable oneDNN optimizations to avoid warnings
os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'  # Fix protobuf issues

# Additional TensorFlow warning suppression
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', message='.*sparse_softmax_cross_entropy.*')
warnings.filterwarnings('ignore', message='.*MessageFactory.*')
warnings.filterwarnings('ignore', message='.*GetPrototype.*')

# Suppress specific library warnings
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
logging.getLogger('google.protobuf').setLevel(logging.ERROR)

try:
    import tensorflow as tf
    tf.get_logger().setLevel('ERROR')  # Only show TF errors
    # Additional TensorFlow configuration
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
except ImportError:
    pass  # TensorFlow not installed

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY')
DEEPSEEK_API_URL = config('DEEPSEEK_API_URL')


ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.User'  # Replace with actual app name


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '*']

# CSRF trusted origins for development (fixes origin checking errors)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters',
    'users',
    'content_ingestion',
    'question_generation',
    'user_learning',
    'minigames',
    'reading',
    'analytics',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# For development, allow all origins
CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials for authentication
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_CREDENTIALS = False

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Ensure headers are added to all responses including errors
CORS_URLS_REGEX = r'^/api/.*$'

# Send CORS headers even for errors
CORS_HANDLE_PREFLIGHT_OPTIONS = True
CORS_EXPOSE_HEADERS = ['*']

# Ensure CORS headers are sent for all responses including 404s
CORS_PREFLIGHT_MAX_AGE = 86400

# Add this to ensure CORS headers on error responses
CORS_URLS_REGEX = r'^/api/.*$'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    #enable JWT
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}



ROOT_URLCONF = 'pygrounds_backend_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pygrounds_backend_new.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'CONN_MAX_AGE': 60,  # Keep connections alive for 60 seconds
        'OPTIONS': {
            'connect_timeout': 10,
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
    },
    'loggers': {
        'user_learning': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# File Upload Settings
# Set maximum file upload size to 25MB (slightly above our 20MB app limit for safety)
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25MB
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
