# Generated by Django 4.2.23 on 2025-09-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readingmaterial",
            options={
                "ordering": [
                    "topic__zone__order",
                    "topic__id",
                    "subtopic__order_in_topic",
                    "order_in_topic",
                    "id",
                ]
            },
        ),
    ]
