# Generated by Django 4.2.24 on 2025-09-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0002_alter_subtopic_options_subtopic_order_in_topic_and_more'),
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='subtopic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content_ingestion.subtopic'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='topic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content_ingestion.topic'),
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
