# Generated by Django 4.2.23 on 2025-07-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="readingmaterial", options={},),
        migrations.AlterUniqueTogether(
            name="readingmaterial", unique_together={("topic", "subtopic", "title")},
        ),
    ]
