# Generated by Django 4.2.23 on 2025-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="readingmaterial",
            constraint=models.UniqueConstraint(
                fields=("topic", "title"), name="unique_topic_title"
            ),
        ),
    ]
