# Generated by Django 4.2.23 on 2025-09-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0002_alter_readingmaterial_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readingmaterial",
            options={
                "ordering": [
                    "topic_ref__zone__order",
                    "topic_ref__id",
                    "subtopic_ref__order_in_topic",
                    "order_in_topic",
                    "id",
                ]
            },
        ),
        migrations.RenameField(
            model_name="readingmaterial", old_name="subtopic", new_name="subtopic_ref",
        ),
        migrations.RenameField(
            model_name="readingmaterial", old_name="topic", new_name="topic_ref",
        ),
    ]
