# Generated by Django 4.2.23 on 2025-08-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0005_constraints_and_cleanup"),
    ]

    operations = []
    
