# Generated by Django 5.1.6 on 2025-12-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_ids', models.JSONField(blank=True, default=list, help_text='List of topic IDs this question covers')),
                ('subtopic_ids', models.JSONField(blank=True, default=list, help_text='List of subtopic IDs this question covers')),
                ('question_text', models.TextField()),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('estimated_difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('estimated_difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20)),
                ('game_type', models.CharField(choices=[('coding', 'Coding'), ('non_coding', 'Non-Coding')], default='non_coding', max_length=20)),
                ('game_data', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='content_ingestion.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='content_ingestion.topic')),
            ],
            options={
                'ordering': ['subtopic__name'],
                'indexes': [models.Index(fields=['subtopic', 'estimated_difficulty'], name='question_ge_subtopi_f3dd14_idx'), models.Index(fields=['validation_status'], name='question_ge_validat_62b536_idx'), models.Index(fields=['topic'], name='question_ge_topic_i_a047ba_idx')],
            },
        ),
    ]
