# Generated by Django 6.0.3 on 2026-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Flag question for review by users during minigames'),
        ),
    ]
