# Generated by Django 5.2.4 on 2025-07-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tocentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='next_entry',
        ),
        migrations.RemoveField(
            model_name='tocentry',
            name='parent',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
        migrations.DeleteModel(
            name='TOCEntry',
        ),
    ]
