# Generated by Django 4.2.24 on 2025-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['game_type', 'estimated_difficulty'], name='question_ge_game_ty_2d56a9_idx'),
        ),
    ]
