# Generated by Django 4.2.23 on 2025-09-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="recalibrated_difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("master", "Master"),
                ],
                help_text="Latest recalibrated difficulty (if any)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
