# Generated by Django 4.2.23 on 2025-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Intermediate"), (3, "Hard")]
                    ),
                ),
            ],
        ),
    ]
