# Generated by Django 5.1.7 on 2025-08-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedquestion',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='minigame_type',
        ),
    ]
