# Generated by Django 5.1.6 on 2025-08-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='answer_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
