# Generated by Django 4.2.23 on 2025-09-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_generation",
            "0002_generatedquestion_question_ge_game_ty_2d56a9_idx",
        ),
        (
            "question_generation",
            "0002_generatedquestion_recalibrated_difficulty_and_more",
        ),
    ]

    operations = []
