# Generated by Django 5.1.6 on 2025-08-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0002_alter_generatedquestion_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
