# Generated by Django 5.1.7 on 2025-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0018_remove_fields'),
        ('question_generation', '0002_remove_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generatedquestion',
            name='question_ge_validat_f95915_idx',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='quality_score',
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['validation_status'], name='question_ge_validat_62b536_idx'),
        ),
    ]
