# Generated by Django 5.1.7 on 2025-07-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_ingestion', '0004_alter_documentchunk_embedding_and_more'),
        ('question_generation', '0002_alter_tocentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkRetrievalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score')),
                ('rank', models.IntegerField(help_text='Rank in retrieval results (1 = highest)')),
                ('chunk_context', models.JSONField(blank=True, default=dict, help_text='Additional context about why this chunk was retrieved')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_ingestion.documentchunk')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_per_subtopic', models.IntegerField(default=5, help_text='Number of questions to generate per subtopic')),
                ('generation_config', models.JSONField(default=dict, help_text='Configuration for question generation (models, prompts, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_subtopics', models.IntegerField(default=0)),
                ('completed_subtopics', models.IntegerField(default=0)),
                ('total_questions_generated', models.IntegerField(default=0)),
                ('failed_subtopics', models.IntegerField(default=0)),
                ('task_results', models.JSONField(blank=True, default=dict, help_text='Detailed results and statistics')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of errors encountered during generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subtopics', models.ManyToManyField(help_text='Subtopics to generate questions for', to='content_ingestion.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Query used for RAG retrieval')),
                ('embedding_model', models.CharField(help_text='Embedding model used for retrieval', max_length=100)),
                ('retrieval_params', models.JSONField(default=dict, help_text='Parameters used for retrieval (top_k, similarity_threshold, etc.)')),
                ('context_window', models.TextField(help_text='Final context window sent to LLM')),
                ('questions_generated', models.IntegerField(default=0)),
                ('generation_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('session_metadata', models.JSONField(blank=True, default=dict, help_text='Additional session information')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_chunks', models.ManyToManyField(help_text='Chunks retrieved by RAG', through='question_generation.ChunkRetrievalScore', to='content_ingestion.documentchunk')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_sessions', to='content_ingestion.subtopic')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='chunkretrievalscore',
            name='rag_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_generation.ragsession'),
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The actual question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('code_completion', 'Code Completion'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('coding_exercise', 'Coding Exercise'), ('explanation', 'Explanation')], default='multiple_choice', max_length=50)),
                ('answer_options', models.JSONField(blank=True, default=list, help_text='List of answer options for multiple choice questions')),
                ('correct_answer', models.TextField(help_text='The correct answer or solution')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of why this is the correct answer')),
                ('estimated_difficulty', models.CharField(blank=True, choices=[('', 'Not Assigned'), ('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='', help_text='Difficulty level - empty for now, to be assigned later', max_length=20)),
                ('rag_context', models.JSONField(blank=True, default=dict, help_text='Context and metadata from RAG retrieval')),
                ('generation_model', models.CharField(blank=True, help_text='Model used to generate this question (e.g., gpt-4, claude-3)', max_length=100)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this question')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about question generation')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score from validation (0.0 - 1.0)', null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_used', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(blank=True, help_text='Success rate when used in practice (0.0 - 1.0)', null=True)),
                ('source_chunks', models.ManyToManyField(blank=True, help_text='Chunks used by RAG to generate this question', to='content_ingestion.documentchunk')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='content_ingestion.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='content_ingestion.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subtopic', 'estimated_difficulty'], name='question_ge_subtopi_f3dd14_idx'), models.Index(fields=['validation_status', 'quality_score'], name='question_ge_validat_f95915_idx'), models.Index(fields=['topic', 'question_type'], name='question_ge_topic_i_f640f9_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chunkretrievalscore',
            unique_together={('rag_session', 'chunk')},
        ),
    ]
