# Generated by Django 4.2.29 on 2026-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0002_generatedquestion_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='flag_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when question was flagged', null=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='flag_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the flag', null=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this question was flagged', null=True),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='flagged_by',
            field=models.CharField(blank=True, help_text='Username of user who flagged', max_length=255, null=True),
        ),
    ]
