# Generated by Django 4.2.23 on 2025-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_generation", "0002_generatedquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedquestion",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner"),
                    (1, "Intermediate"),
                    (2, "Advanced"),
                    (3, "Master"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Beginner"),
                    (1, "Intermediate"),
                    (2, "Advanced"),
                    (3, "Master"),
                ],
                null=True,
            ),
        ),
    ]
