# Generated by Django 5.1.7 on 2025-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0003_remove_explanation_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='buggy_question_text',
            field=models.TextField(blank=True, help_text="Alternative question text for 'fix the buggy code' version (coding questions only)", null=True),
        ),
    ]
