# Generated by Django 5.1.7 on 2025-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='game_type',
            field=models.CharField(choices=[('coding', 'Coding Exercise'), ('non_coding', 'Non-Coding Question')], default='non_coding', help_text='Type of game - coding or non-coding', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='estimated_difficulty',
            field=models.CharField(blank=True, choices=[('', 'Not Assigned'), ('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='beginner', help_text="Difficulty level - starts as 'beginner', can be updated later", max_length=20),
        ),
    ]
