# Generated by Django 5.1.6 on 2025-08-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0003_alter_generatedquestion_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='minigame_type',
            field=models.CharField(choices=[('hangman_coding', 'Hangman-Style Coding Game'), ('ship_debugging', 'Ship Debugging Game'), ('word_search', 'Word Search Puzzle'), ('crossword', 'Crossword Puzzle')], default='generic', max_length=30, null=True),
        ),
    ]
