# Generated by Django 5.1.7 on 2025-08-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0004_generatedquestion_buggy_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedquestion',
            name='buggy_question_text',
        ),
    ]
