# Generated by Django 5.1.7 on 2025-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0004_add_game_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='minigame_type',
            field=models.CharField(choices=[('hangman_coding', 'Hangman-Style Coding Game'), ('ship_debugging', 'Ship Debugging Game'), ('word_search', 'Word Search Puzzle'), ('crossword', 'Crossword Puzzle'), ('generic', 'Generic Question')], default='generic', help_text='Specific minigame type for targeted content generation', max_length=30),
        ),
    ]
