# Generated by Django 5.1.7 on 2025-08-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0005_remove_buggy_question_text_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemanticSubtopic',
        ),
    ]
