# Generated by Django 5.1.7 on 2025-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0005_generatedquestion_minigame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='game_data',
            field=models.JSONField(blank=True, default=dict, help_text='Minigame-specific data like function parameters, validation settings, etc.'),
        ),
    ]
