# Generated by Django 5.1.7 on 2025-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0006_delete_semanticsubtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
