# Generated by Django 5.1.7 on 2025-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0006_generatedquestion_game_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='minigame_type',
            field=models.CharField(choices=[('hangman_coding', 'Hangman-Style Coding Game'), ('ship_debugging', 'Ship Debugging Game'), ('word_search', 'Word Search Puzzle'), ('crossword', 'Crossword Puzzle')], default='generic', help_text='Specific minigame type for targeted content generation', max_length=30),
        ),
    ]
