# Generated by Django 5.1.7 on 2025-07-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0009_alter_documentchunk_options_and_more'),
        ('question_generation', '0007_alter_generatedquestion_minigame_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('estimated_difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20)),
                ('game_type', models.CharField(choices=[('coding', 'Coding'), ('non_coding', 'Non-Coding')], default='non_coding', max_length=20)),
                ('minigame_type', models.CharField(choices=[('hangman_coding', 'Hangman-Style Coding Game'), ('ship_debugging', 'Ship Debugging Game'), ('word_search', 'Word Search Puzzle'), ('crossword', 'Crossword Puzzle')], default='generic', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chunkretrievalscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chunkretrievalscore',
            name='chunk',
        ),
        migrations.RemoveField(
            model_name='chunkretrievalscore',
            name='rag_session',
        ),
        migrations.RemoveField(
            model_name='ragsession',
            name='retrieved_chunks',
        ),
        migrations.RemoveField(
            model_name='questiongenerationtask',
            name='subtopics',
        ),
        migrations.RemoveField(
            model_name='ragsession',
            name='subtopic',
        ),
        migrations.RemoveIndex(
            model_name='generatedquestion',
            name='question_ge_topic_i_f640f9_idx',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='answer_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='estimated_difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='game_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='game_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('non_coding', 'Non-Coding')], default='non_coding', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='generation_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='generation_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='minigame_type',
            field=models.CharField(choices=[('hangman_coding', 'Hangman-Style Coding Game'), ('ship_debugging', 'Ship Debugging Game'), ('word_search', 'Word Search Puzzle'), ('crossword', 'Crossword Puzzle')], default='generic', max_length=30),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='rag_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, to='content_ingestion.documentchunk'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='success_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['topic'], name='question_ge_topic_i_a047ba_idx'),
        ),
        migrations.AddField(
            model_name='preassessmentquestion',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_questions', to='content_ingestion.subtopic'),
        ),
        migrations.AddField(
            model_name='preassessmentquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_questions', to='content_ingestion.topic'),
        ),
        migrations.DeleteModel(
            name='ChunkRetrievalScore',
        ),
        migrations.DeleteModel(
            name='QuestionGenerationTask',
        ),
        migrations.DeleteModel(
            name='RAGSession',
        ),
    ]
