# Generated by Django 5.1.7 on 2025-07-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0008_preassessmentquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='minigame_type',
        ),
    ]
