# Generated by Django 5.1.7 on 2025-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0009_remove_preassessmentquestion_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessmentquestion',
            name='subtopics_covered',
            field=models.JSONField(blank=True, default=list, help_text='List of subtopic names this question covers'),
        ),
        migrations.AddField(
            model_name='preassessmentquestion',
            name='topics_covered',
            field=models.JSONField(blank=True, default=list, help_text='List of topic names this question covers'),
        ),
    ]
