# Generated by Django 5.1.7 on 2025-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0010_preassessmentquestion_subtopics_covered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassessmentquestion',
            name='subtopics_covered',
            field=models.JSONField(blank=True, default=list, help_text='List of subtopic IDs this question covers'),
        ),
        migrations.AlterField(
            model_name='preassessmentquestion',
            name='topics_covered',
            field=models.JSONField(blank=True, default=list, help_text='List of topic IDs this question covers'),
        ),
    ]
