# Generated by Django 5.1.7 on 2025-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0011_update_covered_fields_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preassessmentquestion',
            old_name='subtopics_covered',
            new_name='subtopic_ids',
        ),
        migrations.RenameField(
            model_name='preassessmentquestion',
            old_name='topics_covered',
            new_name='topic_ids',
        ),
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='topic',
        ),
    ]
