# Generated by Django 5.1.7 on 2025-07-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0012_rename_subtopics_covered_preassessmentquestion_subtopic_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preassessmentquestion',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='preassessmentquestion',
            name='created_at',
        ),
    ]
